In [28]:
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt

In [29]:
df = pd.read_csv("../data/curated/By_Electorate_SUDO_Political_Sentiment_Data.csv")

In [30]:
df

,DivisionAb,DivisionName,DivisionId,state,WinningParty2022,WinningParty2019,WinningPercent2022,WinningPercent2019,ChangedWinningParty,ChangeInWinningPercent,2022WinningPartyOwnChangeInPercent,avg_age,avg_educ_years,avg_weekly_income,erp,net_migration,electorate,sentiment
0,BANK,Banks,103.0,NSW,LP,LP,0.562619,0.514405,0,0.048214,0.048214,44.345170,10.395971,1724.385938,246738.93,-3036.45,Banks,0.493040
1,BART,Barton,104.0,NSW,ALP,ALP,0.594147,0.583008,0,0.011139,0.011139,24.572478,5.836013,1002.394852,227039.93,-2025.65,Barton,-0.031850
2,BENN,Bennelong,105.0,NSW,LP,LP,0.569119,0.597164,0,-0.028045,-0.028045,45.152296,11.131568,2021.326875,162306.40,-1868.81,Bennelong,0.239293
3,BERO,Berowra,106.0,NSW,LP,LP,0.656487,0.664454,0,-0.007967,-0.007967,46.354738,10.766596,2238.758108,156042.54,292.56,Berowra,0.372008
4,BLAX,Blaxland,107.0,NSW,ALP,ALP,0.647201,0.694836,0,-0.047636,-0.047636,46.852919,11.058923,1717.899554,339619.52,-5108.64,Blaxland,-0.020776
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,OCON,O'Connor,243.0,WA,LP,LP,0.654147,0.650413,0,0.003734,0.003734,42.276027,10.034398,1322.065422,4159.59,-55.13,O'Connor,0.030662
147,PEAR,Pearce,244.0,WA,LP,LP,0.551914,0.536263,0,0.015652,0.015652,45.577553,11.157102,1798.493767,206934.40,1157.15,Pearce,0.214487
148,PERT,Perth,245.0,WA,ALP,ALP,0.532269,0.533319,0,-0.001050,-0.001050,43.379335,10.537070,1748.971344,88444.12,-781.23,Perth,0.416896
149,SWAN,Swan,247.0,WA,LP,LP,0.532241,0.535920,0,-0.003679,-0.003679,43.826244,10.459728,1690.066390,55132.75,-361.01,Swan,0.416485
150,TANG,Tangney,248.0,WA,LP,LP,0.595047,0.610650,0,-0.015603,-0.015603,43.797041,10.331386,1744.028699,92541.66,-641.40,Tangney,0.361850

In [31]:
df = df.drop(columns=['electorate','DivisionAb','DivisionName', 'DivisionId', 'state', 'erp', 'WinningParty2022', 'WinningParty2019','ChangeInWinningPercent', '2022WinningPartyOwnChangeInPercent'])

In [32]:
df

,WinningPercent2022,WinningPercent2019,ChangedWinningParty,avg_age,avg_educ_years,avg_weekly_income,net_migration,sentiment
0,0.562619,0.514405,0,44.345170,10.395971,1724.385938,-3036.45,0.493040
1,0.594147,0.583008,0,24.572478,5.836013,1002.394852,-2025.65,-0.031850
2,0.569119,0.597164,0,45.152296,11.131568,2021.326875,-1868.81,0.239293
3,0.656487,0.664454,0,46.354738,10.766596,2238.758108,292.56,0.372008
4,0.647201,0.694836,0,46.852919,11.058923,1717.899554,-5108.64,-0.020776
...,...,...,...,...,...,...,...,...
146,0.654147,0.650413,0,42.276027,10.034398,1322.065422,-55.13,0.030662
147,0.551914,0.536263,0,45.577553,11.157102,1798.493767,1157.15,0.214487
148,0.532269,0.533319,0,43.379335,10.537070,1748.971344,-781.23,0.416896
149,0.532241,0.535920,0,43.826244,10.459728,1690.066390,-361.01,0.416485
150,0.595047,0.610650,0,43.797041,10.331386,1744.028699,-641.40,0.361850

In [33]:
df.to_csv("../data/curated/Clean_By_Electorate_SUDO.csv", index=False)

In [34]:
df_y = df[['WinningPercent2022', "WinningPercent2019", "ChangedWinningParty", "sentiment"]]
df_x = df[['avg_age','avg_educ_years', 'avg_weekly_income', 'net_migration']]
df_y.rename({'WinningPercent2022': '2022 Support Percentage', 
             'WinningPercent2019': '2019 Support Percentage',
             'ChangedWinningParty': 'Changing Winning Party Status', 
             'sentiment': 'Twitter Sentiment',
             }, axis=1, inplace=True)
df_x.rename({'avg_age': 'Voter Average Age', 
             'avg_educ_years': 'Average Years of Education',
             'avg_weekly_income': 'Average Weekly Income', 
             'net_migration': 'Internel and Overseas Migration',
             }, axis=1, inplace=True)

/var/folders/qp/92z0mwr134b82hr5m4m3fhc00000gn/T/ipykernel_25039/3215824507.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_y.rename({'WinningPercent2022': '2022 Support Percentage',
/var/folders/qp/92z0mwr134b82hr5m4m3fhc00000gn/T/ipykernel_25039/3215824507.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_x.rename({'avg_age': 'Voter Average Age',

In [35]:
df_x

,Voter Average Age,Average Years of Education,Average Weekly Income,Internel and Overseas Migration
0,44.345170,10.395971,1724.385938,-3036.45
1,24.572478,5.836013,1002.394852,-2025.65
2,45.152296,11.131568,2021.326875,-1868.81
3,46.354738,10.766596,2238.758108,292.56
4,46.852919,11.058923,1717.899554,-5108.64
...,...,...,...,...
146,42.276027,10.034398,1322.065422,-55.13
147,45.577553,11.157102,1798.493767,1157.15
148,43.379335,10.537070,1748.971344,-781.23
149,43.826244,10.459728,1690.066390,-361.01
150,43.797041,10.331386,1744.028699,-641.40

## Plot

In [36]:
# a function to solve for a and b
def best_fit(X, Y):

    xbar = sum(X)/len(X)
    ybar = sum(Y)/len(Y)
    n = len(X) # or len(Y)

    numer = sum([xi*yi for xi,yi in zip(X, Y)]) - n * xbar * ybar
    denum = sum([xi**2 for xi in X]) - n * xbar**2

    b = numer / denum
    a = ybar - b * xbar

    print('best fit line:\ny = {:.2f} + {:.2f}x'.format(a, b))

    return a, b

#Function which returns last word
def lastWord(string):
  str_lst = string.split(" ")
  if string != "2022 Support Percentage" and string != "2019 Support Percentage":
    
    # last word
    return str_lst[-1].lower()
  else:
     return (str_lst[0] + str_lst[-1]).lower()

In [37]:
# draw plot
for x in df_x.columns:
    X = df_x[x]
    for y in df_y.columns:
        Y = df_y[y]
        a, b = best_fit(X, Y)
        plt.figure(figsize=(7,4.8))
        # plot points and fit line
        plt.scatter(X, Y)
        yfit = [a + b * xi for xi in X]
        #plt.plot(X, yfit)


        plt.legend()
        plt.xlabel(x)
        plt.ylabel(y)
        title = x + ' v.s. ' + y
        plt.title(title)
        plt.savefig('../data/image/' + lastWord(x) +'_'+ lastWord(y) + '.png')
        plt.close()

No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.

best fit line:
y = 0.60 + -0.00x
best fit line:
y = 0.56 + 0.00x
best fit line:
y = 0.18 + -0.00x

No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.

best fit line:
y = 0.32 + -0.00x
best fit line:
y = 0.61 + -0.00x
best fit line:
y = 0.54 + 0.00x

No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.

best fit line:
y = 0.28 + -0.02x
best fit line:
y = 0.11 + 0.01x
best fit line:
y = 0.62 + -0.00x

No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.

best fit line:
y = 0.54 + 0.00x
best fit line:
y = 0.22 + -0.00x
best fit line:
y = 0.02 + 0.00x

No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.

best fit line:
y = 0.60 + 0.00x
best fit line:
y = 0.59 + -0.00x
best fit line:
y = 0.06 + 0.00x

No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.

best fit line:
y = 0.24 + -0.00x